version: '3.8'

services:
  character-llm-gen:
    # 使用 GHCR 预构建镜像
    image: ghcr.io/YOUR_USERNAME/character-llm-gen:latest
    # 如果需要本地构建，注释上面一行并取消注释下面一行
    # build: .
    container_name: character-llm-gen
    ports:
      - "7860:7860"
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      # 持久化日志文件
      - ./logs:/app/logs
      # 持久化导出文件
      - ./export:/app/export
      # 持久化配置文件
      - ./config:/app/config
      # 持久化模板文件
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      # 可以在这里设置默认的API密钥（建议使用.env文件）
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - character-llm-network

networks:
  character-llm-network:
    driver: host

# 可选：如果需要单独的数据库服务，可以添加以下配置
# volumes:
#   character_llm_data:
#     driver: local 